// Type Imports
import type { InventoryType } from '@/types/apps/inventoryTypes'

export const db: InventoryType[] = [
  {
    id: 1,
    name: 'Samsung Smart TV 65"',
    description: 'Ultra HD 4K Smart Television',
    type: 'Electronics',
    roomAssigned: 'Living Room',
    brand: 'Samsung',
    serialNumber: 'STV-2024-001',
    currentWorth: 4500,
    warrantyStart: '2024-01-15',
    warrantyEnd: '2026-01-15',
    propertyAssigned: 'Marina Heights 2BR',
    photos: ['/images/avatars/1.png'],
    notes: 'Wall mounted, includes remote'
  },
  {
    id: 2,
    name: 'L-Shaped Sofa Set',
    description: 'Premium leather sectional sofa',
    type: 'Furniture',
    roomAssigned: 'Living Room',
    brand: 'IKEA',
    serialNumber: 'FUR-2024-002',
    currentWorth: 8200,
    warrantyStart: '2024-03-10',
    warrantyEnd: '2027-03-10',
    propertyAssigned: 'Palm Villa Deluxe',
    photos: ['/images/avatars/2.png'],
    notes: 'Grey color, 7-seater'
  },
  {
    id: 3,
    name: 'Split AC Unit 2 Ton',
    description: 'Inverter split air conditioner',
    type: 'HVAC',
    roomAssigned: 'Master Bedroom',
    brand: 'Daikin',
    serialNumber: 'HVAC-2023-003',
    currentWorth: 3200,
    warrantyStart: '2023-06-01',
    warrantyEnd: '2025-06-01',
    propertyAssigned: 'Marina Heights 2BR',
    photos: ['/images/avatars/3.png'],
    notes: 'Annual maintenance due in June'
  },
  {
    id: 4,
    name: 'Bosch Dishwasher',
    description: 'Built-in dishwasher 14 place settings',
    type: 'Appliances',
    roomAssigned: 'Kitchen',
    brand: 'Bosch',
    serialNumber: 'APP-2024-004',
    currentWorth: 2800,
    warrantyStart: '2024-02-20',
    warrantyEnd: '2026-02-20',
    propertyAssigned: 'JVC Family Townhouse',
    photos: ['/images/avatars/4.png'],
    notes: 'Stainless steel finish'
  },
  {
    id: 5,
    name: 'King Size Bed Frame',
    description: 'Upholstered king bed with storage',
    type: 'Furniture',
    roomAssigned: 'Master Bedroom',
    brand: 'PAN Emirates',
    serialNumber: 'FUR-2024-005',
    currentWorth: 5500,
    warrantyStart: '2024-04-01',
    warrantyEnd: '2029-04-01',
    propertyAssigned: 'Palm Villa Deluxe',
    photos: ['/images/avatars/5.png'],
    notes: 'Includes hydraulic storage'
  },
  {
    id: 6,
    name: 'Chandelier Crystal',
    description: 'Modern crystal chandelier for dining area',
    type: 'Lighting',
    roomAssigned: 'Dining Room',
    brand: 'Philips',
    serialNumber: 'LGT-2023-006',
    currentWorth: 1800,
    warrantyStart: '2023-09-15',
    warrantyEnd: '2025-09-15',
    propertyAssigned: 'Downtown Penthouse',
    photos: ['/images/avatars/6.png'],
    notes: 'Dimmable, 12 bulb capacity'
  },
  {
    id: 7,
    name: 'LG Refrigerator 700L',
    description: 'Side-by-side refrigerator with ice maker',
    type: 'Appliances',
    roomAssigned: 'Kitchen',
    brand: 'LG',
    serialNumber: 'APP-2024-007',
    currentWorth: 6000,
    warrantyStart: '2024-01-10',
    warrantyEnd: '2027-01-10',
    propertyAssigned: 'Palm Villa Deluxe',
    photos: ['/images/avatars/7.png'],
    notes: 'Platinum silver color'
  },
  {
    id: 8,
    name: 'Persian Area Rug',
    description: 'Hand-knotted Persian rug 3x5m',
    type: 'Decor',
    roomAssigned: 'Living Room',
    brand: 'Carpet Centre',
    serialNumber: 'DEC-2024-008',
    currentWorth: 12000,
    warrantyStart: '2024-05-01',
    warrantyEnd: '2024-05-01',
    propertyAssigned: 'Saadiyat Beach Villa',
    photos: ['/images/avatars/8.png'],
    notes: 'Dry clean only, premium quality'
  },
  {
    id: 9,
    name: 'Office Desk',
    description: 'Adjustable standing desk with drawers',
    type: 'Furniture',
    roomAssigned: 'Room 2',
    brand: 'IKEA',
    serialNumber: 'FUR-2023-009',
    currentWorth: 2200,
    warrantyStart: '2023-11-01',
    warrantyEnd: '2025-11-01',
    propertyAssigned: 'DIFC Office Suite',
    photos: ['/images/avatars/1.png'],
    notes: 'White oak finish, electric height adjustment'
  },
  {
    id: 10,
    name: 'Water Heater 80L',
    description: 'Electric storage water heater',
    type: 'Plumbing',
    roomAssigned: 'Bathroom',
    brand: 'Ariston',
    serialNumber: 'PLB-2024-010',
    currentWorth: 1500,
    warrantyStart: '2024-02-01',
    warrantyEnd: '2026-02-01',
    propertyAssigned: 'Marina Heights 2BR',
    photos: ['/images/avatars/2.png'],
    notes: 'Installed in utility room'
  },
  {
    id: 11,
    name: 'Microwave Oven',
    description: 'Convection microwave oven 30L',
    type: 'Kitchenware',
    roomAssigned: 'Kitchen',
    brand: 'Samsung',
    serialNumber: 'KIT-2024-011',
    currentWorth: 900,
    warrantyStart: '2024-03-15',
    warrantyEnd: '2026-03-15',
    propertyAssigned: 'JVC Family Townhouse',
    photos: ['/images/avatars/3.png'],
    notes: 'Built-in, stainless steel'
  },
  {
    id: 12,
    name: 'Outdoor Dining Set',
    description: '6-seater outdoor teak dining table with chairs',
    type: 'Outdoor',
    roomAssigned: 'Balcony',
    brand: 'Marina Home',
    serialNumber: 'OUT-2024-012',
    currentWorth: 7500,
    warrantyStart: '2024-04-10',
    warrantyEnd: '2027-04-10',
    propertyAssigned: 'Saadiyat Beach Villa',
    photos: ['/images/avatars/4.png'],
    notes: 'Weather-resistant teak wood'
  },
  {
    id: 13,
    name: 'Washing Machine 9kg',
    description: 'Front load fully automatic washing machine',
    type: 'Appliances',
    roomAssigned: 'Kitchen',
    brand: 'Bosch',
    serialNumber: 'APP-2023-013',
    currentWorth: 3500,
    warrantyStart: '2023-07-20',
    warrantyEnd: '2025-07-20',
    propertyAssigned: 'Dubai Hills 3BR',
    photos: ['/images/avatars/5.png'],
    notes: 'EcoSilence drive motor'
  },
  {
    id: 14,
    name: 'Wall Art Canvas Set',
    description: 'Abstract art canvas 3-piece set',
    type: 'Decor',
    roomAssigned: 'Living Room',
    brand: 'Art Dubai',
    serialNumber: 'DEC-2024-014',
    currentWorth: 2500,
    warrantyStart: '2024-06-01',
    warrantyEnd: '2024-06-01',
    propertyAssigned: 'Downtown Penthouse',
    photos: ['/images/avatars/6.png'],
    notes: 'Gallery wrapped, ready to hang'
  },
  {
    id: 15,
    name: 'Security Camera System',
    description: '8-channel NVR with 4 cameras',
    type: 'Electronics',
    roomAssigned: 'Living Room',
    brand: 'Hikvision',
    serialNumber: 'ELC-2024-015',
    currentWorth: 4000,
    warrantyStart: '2024-01-01',
    warrantyEnd: '2027-01-01',
    propertyAssigned: 'Arabian Ranches Villa',
    photos: ['/images/avatars/7.png'],
    notes: '4K resolution, night vision'
  },
  {
    id: 16,
    name: 'Egyptian Cotton Bedding Set',
    description: '1000 thread count king size bedding',
    type: 'Linen',
    roomAssigned: 'Master Bedroom',
    brand: 'Rivoli',
    serialNumber: 'LIN-2024-016',
    currentWorth: 1200,
    warrantyStart: '2024-05-15',
    warrantyEnd: '2024-05-15',
    propertyAssigned: 'JBR Waterfront 2BR',
    photos: ['/images/avatars/8.png'],
    notes: 'White, includes 2 pillow cases'
  },
  {
    id: 17,
    name: 'Dyson Air Purifier',
    description: 'HEPA air purifier with cool fan',
    type: 'Electronics',
    roomAssigned: 'Master Bedroom',
    brand: 'Dyson',
    serialNumber: 'ELC-2024-017',
    currentWorth: 2800,
    warrantyStart: '2024-02-10',
    warrantyEnd: '2026-02-10',
    propertyAssigned: 'Reem Island 1BR',
    photos: ['/images/avatars/1.png'],
    notes: 'Filter replacement due Oct 2025'
  },
  {
    id: 18,
    name: 'Pool Pump System',
    description: 'Variable speed pool pump with filter',
    type: 'Outdoor',
    roomAssigned: 'Balcony',
    brand: 'Pentair',
    serialNumber: 'OUT-2023-018',
    currentWorth: 5000,
    warrantyStart: '2023-08-01',
    warrantyEnd: '2025-08-01',
    propertyAssigned: 'RAK Beachfront Villa',
    photos: ['/images/avatars/2.png'],
    notes: 'Requires quarterly maintenance'
  },
  {
    id: 19,
    name: 'Smart Door Lock',
    description: 'Fingerprint and keypad smart lock',
    type: 'Electronics',
    roomAssigned: 'Room 1',
    brand: 'Yale',
    serialNumber: 'ELC-2024-019',
    currentWorth: 1800,
    warrantyStart: '2024-03-01',
    warrantyEnd: '2027-03-01',
    propertyAssigned: 'Business Bay Studio',
    photos: ['/images/avatars/3.png'],
    notes: 'Supports up to 100 fingerprints'
  },
  {
    id: 20,
    name: 'Gas Cooktop 5 Burner',
    description: 'Built-in stainless steel gas hob',
    type: 'Kitchenware',
    roomAssigned: 'Kitchen',
    brand: 'Smeg',
    serialNumber: 'KIT-2023-020',
    currentWorth: 3800,
    warrantyStart: '2023-10-15',
    warrantyEnd: '2025-10-15',
    propertyAssigned: 'Corniche Apartment',
    photos: ['/images/avatars/4.png'],
    notes: 'Auto-ignition, cast iron supports'
  }
]
