// Type Imports
import type { PropertyType } from '@/types/apps/propertyTypes'

export const db: PropertyType[] = [
  {
    id: 1,
    propertyName: 'Marina Heights 2BR',
    type: 'Apartment',
    location: 'Dubai Marina',
    city: 'Dubai',
    bedrooms: 2,
    bathrooms: 2,
    area: 1250,
    rent: 'AED 95,000',
    status: 'Occupied',
    image: '/images/avatars/1.png',
    ownerName: 'Ahmed Al Maktoum',
    furnished: 'Furnished'
  },
  {
    id: 2,
    propertyName: 'Palm Villa Deluxe',
    type: 'Villa',
    location: 'Palm Jumeirah',
    city: 'Dubai',
    bedrooms: 5,
    bathrooms: 6,
    area: 5500,
    rent: 'AED 450,000',
    status: 'Occupied',
    image: '/images/avatars/2.png',
    ownerName: 'Fatima Al Nahyan',
    furnished: 'Furnished'
  },
  {
    id: 3,
    propertyName: 'Business Bay Studio',
    type: 'Studio',
    location: 'Business Bay',
    city: 'Dubai',
    bedrooms: 0,
    bathrooms: 1,
    area: 480,
    rent: 'AED 42,000',
    status: 'Vacant',
    image: '/images/avatars/3.png',
    ownerName: 'Mohammed Al Qasimi',
    furnished: 'Semi-Furnished'
  },
  {
    id: 4,
    propertyName: 'JVC Family Townhouse',
    type: 'Townhouse',
    location: 'Jumeirah Village Circle',
    city: 'Dubai',
    bedrooms: 3,
    bathrooms: 3,
    area: 2100,
    rent: 'AED 120,000',
    status: 'Occupied',
    image: '/images/avatars/4.png',
    ownerName: 'Sara Al Falasi',
    furnished: 'Unfurnished'
  },
  {
    id: 5,
    propertyName: 'Reem Island 1BR',
    type: 'Apartment',
    location: 'Al Reem Island',
    city: 'Abu Dhabi',
    bedrooms: 1,
    bathrooms: 1,
    area: 750,
    rent: 'AED 55,000',
    status: 'Vacant',
    image: '/images/avatars/5.png',
    ownerName: 'Khalid Al Habtoor',
    furnished: 'Furnished'
  },
  {
    id: 6,
    propertyName: 'Downtown Penthouse',
    type: 'Penthouse',
    location: 'Downtown Dubai',
    city: 'Dubai',
    bedrooms: 4,
    bathrooms: 5,
    area: 4200,
    rent: 'AED 380,000',
    status: 'Under Maintenance',
    image: '/images/avatars/6.png',
    ownerName: 'Noura Al Ketbi',
    furnished: 'Furnished'
  },
  {
    id: 7,
    propertyName: 'Sharjah Family Flat',
    type: 'Apartment',
    location: 'Al Nahda',
    city: 'Sharjah',
    bedrooms: 3,
    bathrooms: 2,
    area: 1600,
    rent: 'AED 38,000',
    status: 'Occupied',
    image: '/images/avatars/7.png',
    ownerName: 'Omar Al Mansoori',
    furnished: 'Unfurnished'
  },
  {
    id: 8,
    propertyName: 'Yas Island Duplex',
    type: 'Duplex',
    location: 'Yas Island',
    city: 'Abu Dhabi',
    bedrooms: 3,
    bathrooms: 3,
    area: 2300,
    rent: 'AED 140,000',
    status: 'Vacant',
    image: '/images/avatars/8.png',
    ownerName: 'Layla Al Zaabi',
    furnished: 'Semi-Furnished'
  },
  {
    id: 9,
    propertyName: 'Dubai Hills 3BR',
    type: 'Apartment',
    location: 'Dubai Hills Estate',
    city: 'Dubai',
    bedrooms: 3,
    bathrooms: 3,
    area: 1800,
    rent: 'AED 130,000',
    status: 'Occupied',
    image: '/images/avatars/1.png',
    ownerName: 'Ahmed Al Maktoum',
    furnished: 'Furnished'
  },
  {
    id: 10,
    propertyName: 'DIFC Office Suite',
    type: 'Office',
    location: 'DIFC',
    city: 'Dubai',
    bedrooms: 0,
    bathrooms: 2,
    area: 950,
    rent: 'AED 200,000',
    status: 'Occupied',
    image: '/images/avatars/2.png',
    ownerName: 'Fatima Al Nahyan',
    furnished: 'Furnished'
  },
  {
    id: 11,
    propertyName: 'Al Barsha Studio',
    type: 'Studio',
    location: 'Al Barsha',
    city: 'Dubai',
    bedrooms: 0,
    bathrooms: 1,
    area: 400,
    rent: 'AED 32,000',
    status: 'Vacant',
    image: '/images/avatars/3.png',
    ownerName: 'Mohammed Al Qasimi',
    furnished: 'Furnished'
  },
  {
    id: 12,
    propertyName: 'Arabian Ranches Villa',
    type: 'Villa',
    location: 'Arabian Ranches',
    city: 'Dubai',
    bedrooms: 4,
    bathrooms: 4,
    area: 3800,
    rent: 'AED 220,000',
    status: 'Occupied',
    image: '/images/avatars/4.png',
    ownerName: 'Sara Al Falasi',
    furnished: 'Semi-Furnished'
  },
  {
    id: 13,
    propertyName: 'Ajman Tower 2BR',
    type: 'Apartment',
    location: 'Ajman Downtown',
    city: 'Ajman',
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    rent: 'AED 28,000',
    status: 'Vacant',
    image: '/images/avatars/5.png',
    ownerName: 'Khalid Al Habtoor',
    furnished: 'Unfurnished'
  },
  {
    id: 14,
    propertyName: 'Saadiyat Beach Villa',
    type: 'Villa',
    location: 'Saadiyat Island',
    city: 'Abu Dhabi',
    bedrooms: 6,
    bathrooms: 7,
    area: 7000,
    rent: 'AED 550,000',
    status: 'Occupied',
    image: '/images/avatars/6.png',
    ownerName: 'Noura Al Ketbi',
    furnished: 'Furnished'
  },
  {
    id: 15,
    propertyName: 'Motor City Loft',
    type: 'Loft',
    location: 'Motor City',
    city: 'Dubai',
    bedrooms: 1,
    bathrooms: 1,
    area: 850,
    rent: 'AED 60,000',
    status: 'Under Maintenance',
    image: '/images/avatars/7.png',
    ownerName: 'Omar Al Mansoori',
    furnished: 'Furnished'
  },
  {
    id: 16,
    propertyName: 'JBR Waterfront 2BR',
    type: 'Apartment',
    location: 'JBR',
    city: 'Dubai',
    bedrooms: 2,
    bathrooms: 2,
    area: 1400,
    rent: 'AED 110,000',
    status: 'Occupied',
    image: '/images/avatars/8.png',
    ownerName: 'Layla Al Zaabi',
    furnished: 'Furnished'
  },
  {
    id: 17,
    propertyName: 'Silicon Oasis 1BR',
    type: 'Apartment',
    location: 'Dubai Silicon Oasis',
    city: 'Dubai',
    bedrooms: 1,
    bathrooms: 1,
    area: 680,
    rent: 'AED 40,000',
    status: 'Vacant',
    image: '/images/avatars/1.png',
    ownerName: 'Ahmed Al Maktoum',
    furnished: 'Unfurnished'
  },
  {
    id: 18,
    propertyName: 'Corniche Apartment',
    type: 'Apartment',
    location: 'Corniche',
    city: 'Abu Dhabi',
    bedrooms: 2,
    bathrooms: 2,
    area: 1300,
    rent: 'AED 85,000',
    status: 'Occupied',
    image: '/images/avatars/2.png',
    ownerName: 'Fatima Al Nahyan',
    furnished: 'Semi-Furnished'
  },
  {
    id: 19,
    propertyName: 'Al Majaz Flat',
    type: 'Apartment',
    location: 'Al Majaz',
    city: 'Sharjah',
    bedrooms: 2,
    bathrooms: 2,
    area: 1050,
    rent: 'AED 35,000',
    status: 'Vacant',
    image: '/images/avatars/3.png',
    ownerName: 'Mohammed Al Qasimi',
    furnished: 'Unfurnished'
  },
  {
    id: 20,
    propertyName: 'RAK Beachfront Villa',
    type: 'Villa',
    location: 'Al Marjan Island',
    city: 'Ras Al Khaimah',
    bedrooms: 4,
    bathrooms: 4,
    area: 3200,
    rent: 'AED 160,000',
    status: 'Occupied',
    image: '/images/avatars/4.png',
    ownerName: 'Sara Al Falasi',
    furnished: 'Furnished'
  }
]
